In [68]:
# Import dependencies
import pandas as pd
from sqlalchemy import create_engine
import matplotlib.pyplot as plt

In [69]:
# Create the SQLite engine
engine = create_engine('sqlite:///NAPLAN_SQLDB')

In [70]:
# Execute the SQL query and fetch data into a DataFrame
#query = 'SELECT  DOMAIN, PARTICIPATION_NUMBER, PARTICIPATION_RATE, MEAN, NMS, EXEMPT, ABSENT, ASSESSED BANDCOL1, BANDCOL2, BANDCOL3, BANDCOL4, BANDCOL5, BANDCOL6, YEAR_LEVEL FROM naplan_results_clean'
query = 'SELECT CALENDAR_YEAR, YEAR_LEVEL, DOMAIN, STATE, SUBGROUP, ENROLLED_STUDENTS, MEAN, MEAN_CI, MEAN_SD, NMS, NMS_CI, GAIN, GAIN_CI,EXEMPT, ABSENT, ASSESSED, WITHDRAWN, NONATTEMPT, PARTICIPATION_RATE, PARTICIPATION_NUMBER, NOT_STATED, AVERAGE_AGE, YEARS_OF_SCHOOLING, BANDCOL1, BANDCOL2, BANDCOL3, BANDCOL4, BANDCOL5, BANDCOL6, PCTL05, PCTL20, PCTL80, PCTL95, NOD_MEAN_PREV, NOD_NMS_PREV, NOD_MEAN_BASE, NOD_NMS_BASE FROM naplan_results_clean'
data1 = pd.read_sql_query(query, engine)
data1.head()

,CALENDAR_YEAR,YEAR_LEVEL,DOMAIN,STATE,SUBGROUP,ENROLLED_STUDENTS,MEAN,MEAN_CI,MEAN_SD,NMS,...,BANDCOL5,BANDCOL6,PCTL05,PCTL20,PCTL80,PCTL95,NOD_MEAN_PREV,NOD_NMS_PREV,NOD_MEAN_BASE,NOD_NMS_BASE
0,2008,3,Grammar and Punctuation,ACT,Parental Education: Bachelor,167,445.2,NaN,79.7,95.8,...,23.4,37.0,308.7,381.3,513.0,565.4,None,None,None,None
1,2008,3,Grammar and Punctuation,ACT,Parental Education: Certificate,72,396.1,NaN,91.0,90.0,...,15.3,20.3,240.9,319.4,476.6,546.1,None,None,None,None
2,2008,3,Grammar and Punctuation,ACT,Parental Education: Diploma,52,401.4,NaN,69.1,96.9,...,24.2,12.3,283.7,342.1,456.3,519.2,None,None,None,None
3,2008,3,Grammar and Punctuation,ACT,Parental Education: Not stated,4009,419.8,NaN,82.7,93.7,...,23.5,23.9,278.0,351.0,489.8,551.1,None,None,None,None
4,2008,3,Grammar and Punctuation,ACT,Non-LBOTE,3852,421.2,6.2,82.5,94.4,...,23.7,24.6,279.6,352.5,491.1,552.4,None,None,None,None

In [71]:
#Group by Calendar Year and Domain
grouped_data2 = data2.groupby(['CALENDAR_YEAR', 'DOMAIN'])
mean_score_by_year_domain = grouped_data2.mean().astype(int)
mean_score_by_year_domain

                                       PARTICIPATION_RATE  ABSENT  BANDCOL1  \
CALENDAR_YEAR DOMAIN
2008          Grammar and Punctuation                  94       5        92
              Numeracy                                 94       5        92
              Reading                                  94       5        92
              Spelling                                 94       5        92
2009          Grammar and Punctuation                  95       4        93
...                                                   ...     ...       ...
2022          Grammar and Punctuation                  85      10        83
              Numeracy                                 85      11        82
              Reading                                  87       9        85
              Spelling                                 85      10        82
              Writing                                  86      10        84

                                       BANDCOL2  BANDCOL3  BANDCOL4  BANDCOL5  \
CALENDAR_YEAR DOMAIN
2008          Grammar and Punctuation        14        23        23        15
              Numeracy                       17        26        24        14
              Reading                        15        23        24        16
              Spelling                       13        23        25        16
2009          Grammar and Punctuation        13        21        23        17
...                                         ...       ...       ...       ...
2022          Grammar and Punctuation        15        22        22        13
              Numeracy                       18        26        23        12
              Reading                        14        22        23        15
              Spelling                       14        22        23        15
              Writing                        15        22        23        14

                                       BANDCOL6  YEAR_LEVEL
CALENDAR_YEAR DOMAIN
2008          Grammar and Punctuation         9           6
              Numeracy                        7           6
              Reading                         8           6
              Spelling                        7           6
2009          Grammar and Punctuation        11           6
...                                         ...         ...
2022          Grammar and Punctuation         8           5
              Numeracy                        5           5
              Reading                         9           5
              Spelling                        8           5
              Writing                         5           5

[67 rows x 9 columns]

In [75]:
#group by type
group_dom = data1.groupby(['DOMAIN'])
group_cal_yr = data1.groupby(['CALENDAR_YEAR'])

In [84]:
# student year grouped 'Domain' per year level
Group_Yr3 = data1.loc[data1['YEAR_LEVEL'] == 3].groupby(['DOMAIN', 'CALENDAR_YEAR'])
Group_Yr5 = data1.loc[data1['YEAR_LEVEL'] == 5].groupby(['DOMAIN', 'CALENDAR_YEAR'])
Group_Yr7 = data1.loc[data1['YEAR_LEVEL'] == 7].groupby(['DOMAIN', 'CALENDAR_YEAR'])
Group_Yr9 = data1.loc[data1['YEAR_LEVEL'] == 9].groupby(['DOMAIN', 'CALENDAR_YEAR'])

In [85]:
print(Group_Yr3.groups.keys())
print(Group_Yr5.groups.keys())
print(Group_Yr7.groups.keys())
print(Group_Yr9.groups.keys())

dict_keys([('Grammar and Punctuation', 2008), ('Grammar and Punctuation', 2009), ('Grammar and Punctuation', 2010), ('Grammar and Punctuation', 2011), ('Grammar and Punctuation', 2012), ('Grammar and Punctuation', 2013), ('Grammar and Punctuation', 2014), ('Grammar and Punctuation', 2015), ('Grammar and Punctuation', 2016), ('Grammar and Punctuation', 2017), ('Grammar and Punctuation', 2018), ('Grammar and Punctuation', 2019), ('Grammar and Punctuation', 2021), ('Grammar and Punctuation', 2022), ('Numeracy', 2008), ('Numeracy', 2009), ('Numeracy', 2010), ('Numeracy', 2011), ('Numeracy', 2012), ('Numeracy', 2013), ('Numeracy', 2014), ('Numeracy', 2015), ('Numeracy', 2016), ('Numeracy', 2017), ('Numeracy', 2018), ('Numeracy', 2019), ('Numeracy', 2021), ('Numeracy', 2022), ('Reading', 2008), ('Reading', 2009), ('Reading', 2010), ('Reading', 2011), ('Reading', 2012), ('Reading', 2013), ('Reading', 2014), ('Reading', 2015), ('Reading', 2016), ('Reading', 2017), ('Reading', 2018), ('Reading', 2019), ('Reading', 2021), ('Reading', 2022), ('Spelling', 2008), ('Spelling', 2009), ('Spelling', 2010), ('Spelling', 2011), ('Spelling', 2012), ('Spelling', 2013), ('Spelling', 2014), ('Spelling', 2015), ('Spelling', 2016), ('Spelling', 2017), ('Spelling', 2018), ('Spelling', 2019), ('Spelling', 2021), ('Spelling', 2022), ('Writing', 2011), ('Writing', 2012), ('Writing', 2013), ('Writing', 2014), ('Writing', 2015), ('Writing', 2016), ('Writing', 2017), ('Writing', 2018), ('Writing', 2019), ('Writing', 2021), ('Writing', 2022)])
dict_keys([('Grammar and Punctuation', 2008), ('Grammar and Punctuation', 2009), ('Grammar and Punctuation', 2010), ('Grammar and Punctuation', 2011), ('Grammar and Punctuation', 2012), ('Grammar and Punctuation', 2013), ('Grammar and Punctuation', 2014), ('Grammar and Punctuation', 2015), ('Grammar and Punctuation', 2016), ('Grammar and Punctuation', 2017), ('Grammar and Punctuation', 2018), ('Grammar and Punctuation', 2019), ('Grammar and Punctuation', 2021), ('Grammar and Punctuation', 2022), ('Numeracy', 2008), ('Numeracy', 2009), ('Numeracy', 2010), ('Numeracy', 2011), ('Numeracy', 2012), ('Numeracy', 2013), ('Numeracy', 2014), ('Numeracy', 2015), ('Numeracy', 2016), ('Numeracy', 2017), ('Numeracy', 2018), ('Numeracy', 2019), ('Numeracy', 2021), ('Numeracy', 2022), ('Reading', 2008), ('Reading', 2009), ('Reading', 2010), ('Reading', 2011), ('Reading', 2012), ('Reading', 2013), ('Reading', 2014), ('Reading', 2015), ('Reading', 2016), ('Reading', 2017), ('Reading', 2018), ('Reading', 2019), ('Reading', 2021), ('Reading', 2022), ('Spelling', 2008), ('Spelling', 2009), ('Spelling', 2010), ('Spelling', 2011), ('Spelling', 2012), ('Spelling', 2013), ('Spelling', 2014), ('Spelling', 2015), ('Spelling', 2016), ('Spelling', 2017), ('Spelling', 2018), ('Spelling', 2019), ('Spelling', 2021), ('Spelling', 2022), ('Writing', 2011), ('Writing', 2012), ('Writing', 2013), ('Writing', 2014), ('Writing', 2015), ('Writing', 2016), ('Writing', 2017), ('Writing', 2018), ('Writing', 2019), ('Writing', 2021), ('Writing', 2022)])
dict_keys([('Grammar and Punctuation', 2008), ('Grammar and Punctuation', 2009), ('Grammar and Punctuation', 2010), ('Grammar and Punctuation', 2011), ('Grammar and Punctuation', 2012), ('Grammar and Punctuation', 2013), ('Grammar and Punctuation', 2014), ('Grammar and Punctuation', 2015), ('Grammar and Punctuation', 2016), ('Grammar and Punctuation', 2017), ('Grammar and Punctuation', 2018), ('Grammar and Punctuation', 2019), ('Grammar and Punctuation', 2021), ('Grammar and Punctuation', 2022), ('Numeracy', 2008), ('Numeracy', 2009), ('Numeracy', 2010), ('Numeracy', 2011), ('Numeracy', 2012), ('Numeracy', 2013), ('Numeracy', 2014), ('Numeracy', 2015), ('Numeracy', 2016), ('Numeracy', 2017), ('Numeracy', 2018), ('Numeracy', 2019), ('Numeracy', 2021), ('Numeracy', 2022), ('Reading', 2008), ('Reading', 2009), ('Reading', 2010), ('Reading', 2011), ('Reading', 2012), ('Reading', 2013), ('Reading', 2014), ('Reading', 2015), ('Reading', 2016), ('Reading', 2017), ('Reading', 2018), ('Reading', 2019), ('Reading', 2021), ('Reading', 2022), ('Spelling', 2008), ('Spelling', 2009), ('Spelling', 2010), ('Spelling', 2011), ('Spelling', 2012), ('Spelling', 2013), ('Spelling', 2014), ('Spelling', 2015), ('Spelling', 2016), ('Spelling', 2017), ('Spelling', 2018), ('Spelling', 2019), ('Spelling', 2021), ('Spelling', 2022), ('Writing', 2011), ('Writing', 2012), ('Writing', 2013), ('Writing', 2014), ('Writing', 2015), ('Writing', 2016), ('Writing', 2017), ('Writing', 2018), ('Writing', 2019), ('Writing', 2021), ('Writing', 2022)])
dict_keys([('Grammar and Punctuation', 2008), ('Grammar and Punctuation', 2009), ('Grammar and Punctuation', 2010), ('Grammar and Punctuation', 2011), ('Grammar and Punctuation', 2012), ('Grammar and Punctuation', 2013), ('Grammar and Punctuation', 2014), ('Grammar and Punctuation', 2015), ('Grammar and Punctuation', 2016), ('Grammar and Punctuation', 2017), ('Grammar and Punctuation', 2018), ('Grammar and Punctuation', 2019), ('Grammar and Punctuation', 2021), ('Grammar and Punctuation', 2022), ('Numeracy', 2008), ('Numeracy', 2009), ('Numeracy', 2010), ('Numeracy', 2011), ('Numeracy', 2012), ('Numeracy', 2013), ('Numeracy', 2014), ('Numeracy', 2015), ('Numeracy', 2016), ('Numeracy', 2017), ('Numeracy', 2018), ('Numeracy', 2019), ('Numeracy', 2021), ('Numeracy', 2022), ('Reading', 2008), ('Reading', 2009), ('Reading', 2010), ('Reading', 2011), ('Reading', 2012), ('Reading', 2013), ('Reading', 2014), ('Reading', 2015), ('Reading', 2016), ('Reading', 2017), ('Reading', 2018), ('Reading', 2019), ('Reading', 2021), ('Reading', 2022), ('Spelling', 2008), ('Spelling', 2009), ('Spelling', 2010), ('Spelling', 2011), ('Spelling', 2012), ('Spelling', 2013), ('Spelling', 2014), ('Spelling', 2015), ('Spelling', 2016), ('Spelling', 2017), ('Spelling', 2018), ('Spelling', 2019), ('Spelling', 2021), ('Spelling', 2022), ('Writing', 2011), ('Writing', 2012), ('Writing', 2013), ('Writing', 2014), ('Writing', 2015), ('Writing', 2016), ('Writing', 2017), ('Writing', 2018), ('Writing', 2019), ('Writing', 2021), ('Writing', 2022)])